---
- hosts: TargetServer
  vars:
    user: "{{ user }}"
    version: "{{ version }}"
  become: yes
  tasks:
  - name: Install java
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Install Maven
    yum:
      name: maven
      state: present
  - name: Add Tomcat Group
    group:
      name: tomcat
  - name: Add Tomcat User
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no
  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755
  - name: Download Latest Tomcat and Extract
    unarchive:
      src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]
  - name: Change ownership
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory
  - name: Create tomcat.service
    file:
      path: /etc/systemd/system/tomcat.service
      state: touch
  - name: Edit tomcat.service
    blockinfile:
      dest: /etc/systemd/system/tomcat.service
      insertafter:
      block: |
          [Unit]
          Description = Apache Tomcat 9
          After = syslog.target network.target
          [Service]
          User = tomcat
          Group = tomcat
          Type = oneshot
          PIDFile =/opt/tomcat/apache-tomcat-9.0.46/tomcat.pid
          RemainAfterExit = yes
          ExecStart =/opt/tomcat/apache-tomcat-9.0.46/bin/startup.sh
          ExecStop =/opt/tomcat/apache-tomcat-9.0.46/bin/shutdown.sh
          ExecReStart =/opt/tomcat/apache-tomcat-9.0.46/bin/shutdown.sh;/usr/local/apache-tomcat-9.0.46/bin/startup.sh
          [Install]
          WantedBy = multi-user.target
  - name: chmod 755 tomcat.service
    file:
      path: /etc/systemd/system/tomcat.service
      mode: 0755
  - name: Start Tomcat
    systemd:
      name: tomcat
      state: started
      enabled: yes
  - name: Install Docker
    yum:
      name: docker
      state: present
#  - name: Start and Enable Docker Service
#    service:
#      name: docker
#      state: started
#      enabled: true
  - name: Starting to Deploy Application
    command: sudo docker run -itd -p 8081:8888 --name batch10 "{{ user }}"/batch10:"{{ version }}"
  handlers:
  - name: Running Upddates
    yum:
      update_cache: yes
