---
- hosts: TargetServer
  vars:
    user: "{{ user }}"
    version: "{{ version }}"
  become: yes
  tasks:
  - name: Install java
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Install Maven
    yum:
      name: maven
      state: present
  - name: Add Tomcat Group
    group:
      name: tomcat
  - name: Add Tomcat User
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no
  - name: Create /opt/tomcat Directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755
  - name: Download Latest Tomcat and Extract
    unarchive:
      src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]
  - name: Change Ownership for Tomcat Installation
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory
  - name: Create tomcat.service
    file:
      path: /etc/systemd/system/tomcat.service
      state: touch
  - name: Edit tomcat.service
    blockinfile:
      dest: /etc/systemd/system/tomcat.service
      insertafter:
      block: |
          [Unit]
          Description=Apache Tomcat 9
          After=network.target

          [Service]
          Type=forking

          Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
          Environment=CATALINA_HOME=/opt/tomcat
          Environment=CATALINA_BASE=/opt/tomcat
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'
          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh

          User=tomcat
          Group=tomcat
          UMask=0007
          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target
  - name: Changing Permissions for tomcat.service file
    file:
      path: /etc/systemd/system/tomcat.service
      mode: 0755
  - name: Start Tomcat
    systemd:
      name: tomcat
      state: started
      enabled: yes
      daemon_reload: yes
  - name: Install Docker
    yum:
      name: docker
      state: installed
  - name: Start and Enable Docker Service
    service:
      name: docker
      state: started
      enabled: yes
  - name: Starting to Deploy Application
    command: sudo docker run -itd -p 8081:8888 --name batch10 "{{ user }}"/batch10:"{{ version }}"
  handlers:
  - name: Running Upddates
    yum:
      update_cache: yes
